version: '3.9'

services:
  nginx:
    build:
      context: ./nginx
    container_name: custom_nginx
    ports:
      - "8080:80"
    depends_on:
      - flask
    networks:
      - app-network
    restart: always

  flask:
    build:
      context: ./flask
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  db:
    image: mysql:8.0
    container_name: custom_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db_data:

